
var one = document.getElementById('one');
var two = document.getElementById('two');
var three = document.getElementById('three');



document.getElementById('QuestionType').addEventListener('change',()=>{
    if(document.getElementById('QuestionType').value ==='Students'){
        console.log('student')
        student++;
        document.getElementById('btngroup').children[0].style.display = 'none';
        document.getElementById('btngroup').children[2].style.display = 'none';
        for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
            const element = document.getElementsByClassName('ans')[index];
            element.style.display='none'
        }
    }else{
        console.log('teacher')
        document.getElementById('btngroup').children[0].style.display = 'block';
        document.getElementById('btngroup').children[2].style.display = 'block';
        for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
            const element = document.getElementsByClassName('ans')[index];
            
            element.style.display='block'
        }
    }
})


document.getElementById('inputTag').addEventListener('change',()=>{
    var inputImage = document.getElementById('inputTag').files[0];

    var url =  URL.createObjectURL(inputImage);
    document.getElementById('putimage').innerHTML = `<img id='demologo' src='`+ url+`' class='inimg'>`;
    var img = document.getElementById('demologo');
    setTimeout(()=>{
        const canvas = document.createElement('canvas');
   const ctx = canvas.getContext('2d');
   canvas.width = img.width + 300;
   canvas.height = img.height;
   var ratioX = canvas.width / img.naturalWidth;
var ratioY = canvas.height / img.naturalHeight;
var ratio = Math.min(ratioX, ratioY);
ctx.drawImage(img, 300, 0, img.naturalWidth * ratio, img.naturalHeight * ratio);
   var dataUrl = canvas.toDataURL('image/png');
   document.getElementById('logo').src = dataUrl;
    },1000)
})
function four(){
    document.getElementById('firstpart').innerHTML = document.getElementById('header').innerHTML ;
    document.getElementById('fourContainer').innerHTML +=  document.getElementById('question').innerHTML ;
    
}

function Export(filename = ''){
    const imgAll = document.getElementById('fourContainer').querySelectorAll('img')
for(let i =0; i < imgAll.length; i++){
    if(imgAll[i].src.includes('window.location.href')){}
    else{var oldurl = imgAll[i].src;
        imgAll[i].src =  oldurl;}   
}  

    var preHtml = `<!DOCTYPE html xmlns:v="urn:schemas-microsoft-com:vml"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:w="urn:schemas-microsoft-com:office:word"
    xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
    xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><title>Question Generated By Gourab Das</title>
    <style type="text/css">
    #student,#marks,#duration{margin-left:0.3in;}
    .circle{
        width: 1.5vw;
        height: 1.5vw;
        display: inline-block;
        background: #fbf8f8;
        border: 2px solid #0aaade;
        border-radius: 2vw;
        margin-left: 1vw;
    }
    .square{
        width: 1.5vw;
        height: 1.5vw;
        display: inline-block;
        background: #fbf8f8;
        border: 2px solid #0aaade;
        border-radius: 0.3vw;
        margin-left: 1vw;
    }
    #logo{
        position:absolute;margin-left:50px;
    }
    body ol{font-size:20px;font-family:'Calibri';left:-30px;list-style:lower-alpha;}
    body ol li{margin-left: 40px;font-size:18px;margin-top: 5px;}
    @page
    {
        mso-page-orientation: potrait;  size:8.5in 11in;
    }@page Section1 {margin:0.5in 0.5in 0.5in 0.5in;size:595.45pt 841.7pt;mso-page-orientation:potrait;mso-header-margin:0.5in;mso-header: h1;mso-footer-margin:0.5in;mso-footer:f1;}div.Section1 {page:Section1;}p.headerFooter { margin:0in; text-align: center; }</style></head><body>`;
    var postHtml = "</body></html>";

var c =`<div class=Section1><table style='margin-left:50in;'><tr style='height:1pt;mso-height-rule:exactly'><td><div style='mso-element:footer' id=f1>Generated By Gourab Das <p class=headerFooter>Page	&nbsp;	&nbsp;<span style='mso-field-code:PAGE'></span>	&nbsp;of	&nbsp;<span style='mso-field-code:NUMPAGES'></span></p></div>&nbsp;</td></tr></table>`;


    var html = preHtml+ c + document.getElementById('fourContainer').innerHTML+postHtml;

    var blob = new Blob(['\ufeff', html], {
        type: 'application/msword'
    });  
    var url = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(html);  
    filename = filename?filename+'.doc':'Question Generated By Gourab Das.doc';   
    var downloadLink = document.createElement("a");
    document.body.appendChild(downloadLink);   
    if(navigator.msSaveOrOpenBlob ){
        navigator.msSaveOrOpenBlob(blob, filename);
    }else{
        downloadLink.href = url;     
        downloadLink.download = filename;      
        downloadLink.click();
    }  
}
function ExportStudent(filename = ''){
    const imgAll = document.getElementById('fourContainer').querySelectorAll('img')
for(let i =0; i < imgAll.length; i++){
    if(imgAll[i].src.includes('window.location.href')){}
    else{var oldurl = imgAll[i].src;
        imgAll[i].src =  oldurl;}
    
}  

    var preHtml = `<!DOCTYPE html xmlns:v="urn:schemas-microsoft-com:vml"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:w="urn:schemas-microsoft-com:office:word"
    xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
    xmlns="https://www.w3.org/TR/html53/"><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><title>Question Generated By Nueberg</title>
    <style type="text/css">
    #student,#marks,#duration{margin-left:0.3in;}
    .ans{display:none;}
    body ol{font-size:20px;font-family:'Calibri';left:-30px;list-style:lower-alpha;}
    body ol li{margin-left: 40px;font-size:18px;margin-top: 5px;}
    .hint {
        display: flex;
    }
    .hint span {
        display: flex;
        align-items: center;
        margin-left: 2vw;
    }
    .circle{
        width: 1.5vw;
        height: 1.5vw;
        display: inline-block;
        background: #fbf8f8;
        border: 2px solid #0aaade;
        border-radius: 2vw;
        margin-left: 1vw;
    }
    .square{
        width: 1.5vw;
        height: 1.5vw;
        display: inline-block;
        background: #fbf8f8;
        border: 2px solid #0aaade;
        border-radius: 0.3vw;
        margin-left: 1vw;
    }
    @page
    {
        mso-page-orientation: potrait;  size:8.5in 11in;
    }@page Section1 {margin:0.5in 0.5in 0.5in 0.5in;size:595.45pt 841.7pt;mso-page-orientation:potrait;mso-header-margin:0.5in;mso-header: h1;mso-footer-margin:0.5in;mso-footer:f1;}div.Section1 {page:Section1;}p.headerFooter { margin:0in; text-align: center; }</style></head><body>`;
    var postHtml = "</body></html>";

var c =`<div class=Section1><table style='margin-left:50in;'><tr style='height:1pt;mso-height-rule:exactly'><td><div style='mso-element:footer' id=f1>Generated By Gourab Das <p class=headerFooter>Page	&nbsp;	&nbsp;<span style='mso-field-code:PAGE'></span>	&nbsp;of	&nbsp;<span style='mso-field-code:NUMPAGES'></span></p></div>&nbsp;</td></tr></table>`;


    var html = preHtml+ c + document.getElementById('fourContainer').innerHTML+postHtml;

    var blob = new Blob(['\ufeff', html], {
        type: 'application/msword'
    });  
    var url = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(html);  
    filename = filename?filename+'.doc':'Question Generated By Gourab Das.doc';   
    var downloadLink = document.createElement("a");
    document.body.appendChild(downloadLink);   
    if(navigator.msSaveOrOpenBlob ){
        navigator.msSaveOrOpenBlob(blob, filename);
    }else{
        downloadLink.href = url;     
        downloadLink.download = filename;      
        downloadLink.click();
    }  
}

function chgPic(){
   // const imgAll = document.getElementById('fourContainer').querySelectorAll('img')
//     for(let i =1; i < imgAll.length; i++){
//         var img= new Image();
//         img.src=imgAll[i].src;
//         img.onload=()=>{
//              canvas = document.createElement('canvas');
//              ctx = canvas.getContext('2d');
//             canvas.width = img.width;
//    canvas.height = img.height;
//    var ratioX = canvas.width / img.naturalWidth;
//    var ratioY = canvas.height / img.naturalHeight;
//    var ratio = Math.min(ratioX, ratioY);
//    ctx.drawImage(img, 0, 0, img.naturalWidth * ratio, img.naturalHeight * ratio);
//    var dataUrl = canvas.toDataURL('image/png');
//    imgAll[i].src=dataUrl;
//    canvas.remove()
//         }

//     }
 var i =1;  10
 function imgchng(){
    if(i < imgAll.length){
        var img= new Image();
        img.src=imgAll[i].src;
        img.onload=()=>{
             canvas = document.createElement('canvas');
             ctx = canvas.getContext('2d');
            canvas.width = img.width;
   canvas.height = img.height;
   var ratioX = canvas.width / img.naturalWidth;
   var ratioY = canvas.height / img.naturalHeight;
   var ratio = Math.min(ratioX, ratioY);
   ctx.drawImage(img, 0, 0, img.naturalWidth * ratio, img.naturalHeight * ratio);
   var dataUrl = canvas.toDataURL('image/png');
   imgAll[i].src=dataUrl;
   canvas.remove();
   i++;
   imgchng();
        }
    }
 }
 imgchng();
}

function Exportpdf(){ 
    const imgAll = document.getElementById('fourContainer').querySelectorAll('img');
    if(imgAll.length>1){
        var i =1; 
        function imgchng(){
           if(i < imgAll.length){
               var img= new Image();
               img.src=imgAll[i].src;
               img.onload=()=>{
                    canvas = document.createElement('canvas');
                    ctx = canvas.getContext('2d');
                   canvas.width = img.width;
          canvas.height = img.height;
          var ratioX = canvas.width / img.naturalWidth;
          var ratioY = canvas.height / img.naturalHeight;
          var ratio = Math.min(ratioX, ratioY);
          ctx.drawImage(img, 0, 0, img.naturalWidth * ratio, img.naturalHeight * ratio);
          var dataUrl = canvas.toDataURL('image/png');
          imgAll[i].src=dataUrl;
          canvas.remove();
          i++;
          console.log(imgAll.length,i)
          if(i==imgAll.length){
            setTimeout(()=>{
                var printContents = document.getElementById('fourContainer').innerHTML;
                var w = window.open();
                w.document.head.innerHTML = '<title> Question Generated By Gourab Das </title><style type="text/css"> #logo{left: -153px;position: relative;} body ol li{margin-left: 40px;margin-top: 5px;} body ol{    list-style: lower-latin;} .circle{width: 1.5vw;height: 1.5vw;display: inline-block; background: #fbf8f8; border: 2px solid #0aaade;border-radius: 2vw;margin-left: 1vw;} .square{width: 1.5vw;height: 1.5vw;display: inline-block; background: #fbf8f8; border: 2px solid #0aaade; border-radius: 0.3vw; margin-left: 1vw; }   .hint {display: flex;} .hint span {display: flex;align-items: center;margin-left: 2vw;}</style>'
                w.document.body.innerHTML = printContents + '<script> window.close() </script>';
                w.print();  
                w.close();
                setTimeout(()=>{w.close();},300) 
            },200)
          }
          imgchng();
               }}}
        imgchng();
    }
    else{
        var printContents = document.getElementById('fourContainer').innerHTML;
        var w = window.open();
        w.document.head.innerHTML = '<title> Question Generated By Gourab Das </title><style type="text/css"> #logo{left: -153px;position: relative;} body ol li{margin-left: 40px;margin-top: 5px;} body ol{    list-style: lower-latin;} .circle{width: 1.5vw;height: 1.5vw;display: inline-block; background: #fbf8f8; border: 2px solid #0aaade;border-radius: 2vw;margin-left: 1vw;} .square{width: 1.5vw;height: 1.5vw;display: inline-block; background: #fbf8f8; border: 2px solid #0aaade; border-radius: 0.3vw; margin-left: 1vw; }   .hint {display: flex;} .hint span {display: flex;align-items: center;margin-left: 2vw;}</style>'
        w.document.body.innerHTML = printContents + '<script> window.close() </script>';
        w.print();  
        w.close();
        setTimeout(()=>{w.close();},300) 
    }
    
   }
    
function ExportpdfStudent(){
    const imgAll = document.getElementById('fourContainer').querySelectorAll('img');
    if(imgAll.length>1){
        var i =1; 
    function imgchng(){
       if(i < imgAll.length){
           var img= new Image();
           img.src=imgAll[i].src;
           img.onload=()=>{
                canvas = document.createElement('canvas');
                ctx = canvas.getContext('2d');
               canvas.width = img.width;
      canvas.height = img.height;
      var ratioX = canvas.width / img.naturalWidth;
      var ratioY = canvas.height / img.naturalHeight;
      var ratio = Math.min(ratioX, ratioY);
      ctx.drawImage(img, 0, 0, img.naturalWidth * ratio, img.naturalHeight * ratio);
      var dataUrl = canvas.toDataURL('image/png');
      imgAll[i].src=dataUrl;
      canvas.remove();
      i++;
      console.log(imgAll.length,i)
      if(i==imgAll.length){
        setTimeout(()=>{
            for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
                const element = document.getElementsByClassName('ans')[index];
                
                element.style.display='none'
            }
            var printContents = document.getElementById('fourContainer').innerHTML;
            var w = window.open();
            w.document.head.innerHTML = '<title> Question Generated By Gourab Das </title><style type="text/css">.ans{display:none;}#logo{left: -153px;position: relative;}body ol{    list-style: lower-latin;}body ol li{margin-left: 40px;margin-top: 5px;}</style>'
            w.document.body.innerHTML = printContents + '<script> window.close() </script>';
            w.print();  
            w.close();
           setTimeout(()=>{w.close();},300) 
            if(document.getElementById('QuestionType').value=='Teachers'){
                for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
                    const element = document.getElementsByClassName('ans')[index];
                    
                    element.style.display='block';
                }
            }
        },200)
      }
      imgchng();
           }}}
    imgchng();
    }
    else{
        for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
            const element = document.getElementsByClassName('ans')[index];
            
            element.style.display='none'
        }
        var printContents = document.getElementById('fourContainer').innerHTML;
            var w = window.open();
            w.document.head.innerHTML = '<title> Question Generated By Gourab Das </title><style type="text/css">.ans{display:none;}#logo{left: -153px;position: relative;}body ol{    list-style: lower-latin;}body ol li{margin-left: 40px;margin-top: 5px;}</style>'
            w.document.body.innerHTML = printContents + '<script> window.close() </script>';
            w.print();  
            w.close();
            if(document.getElementById('QuestionType').value=='Teachers'){
                for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
                    const element = document.getElementsByClassName('ans')[index];
                    
                    element.style.display='block';
                }
            }
    }
    
}
document.getElementById('TestName').addEventListener('change',()=>{
    document.getElementById('TName').innerHTML = 'Test Name - '+ document.getElementById('TestName').value;
    document.getElementById('test').innerHTML =  document.getElementById('TestName').value;
})
document.getElementById('TotalTime').addEventListener('change',()=>{
    document.getElementById('time').innerHTML = 'Test Duration : '+document.getElementById('TotalTime').value + ' Mins';
    document.getElementById('duration').innerHTML = 'Test Duration : '+ document.getElementById('TotalTime').value + ' Mins';   
})
document.getElementById('TotalMarks').addEventListener('change',()=>{
    document.getElementById('infomarks').innerHTML = 'Total Marks :  '+document.getElementById('TotalMarks').value ;
    document.getElementById('marks').innerHTML = 'Total Marks : '+document.getElementById('TotalMarks').value ;
})

var QuestionMode = 'Auto';
var pgno = 0;
const step1 = ()=> {
    var inp = document.getElementById('one').querySelectorAll('input');
    if(inp[0].value!==''&inp[1].value!==''&inp[2].value!==''){
        secpage(); pgno++;document.getElementById('one').style.display='none';document.getElementById('two').style.display='block';document.getElementById('previous').style.display='block';
    }
    for(let i=0;i<3;i++){
                        if(inp[i].value == ''){
                            inp[i].style.border = '1px solid #f44336';
                            setTimeout(()=>{inp[i].style.border='1px solid #bababa'},1300)
                        }
                    }
}
var checking=[];
var go=0;
const step3 = ()=>{
    go=0;
    checking=[];
    var allin =document.getElementById('selectQuestion').querySelectorAll('input');
    for(input of allin){
        if(input.getAttribute('name')==='Q'){
            if(input.value != ''){
             checking.push(input)
            }
        }
    }
    if(checking.length >0){
        checking.forEach(e => {
            if(e.nextElementSibling.value ==='' || e.nextElementSibling.value<1){
                e.nextElementSibling.style.border = '1px solid #f44336';
                go++
                setTimeout(()=>{e.nextElementSibling.style.border='1px solid #bababa'},1300);
                return;
            }
        })
        if(go<1){
            console.log(checking)
            gopass();
        }
    }
    
}
const gopass =()=>{
    forthpage();pgno++;document.getElementById('previous').style.left='-23vw';document.getElementById('three').style.display='block';document.getElementById('selectQuestion').style.display='none';document.getElementById('customQuestion').style.display='none';if(QuestionMode != 'Auto'){cquestion();document.getElementById('next').style.left='43.5vw'};if(QuestionMode === 'Auto'){question()};
}
var checkingC = 0;
var checkingCInput =0;
const step3c = ()=>{
    checkingC = 0;
    checkingCInput =0;
    var inputsfill = document.getElementById('OBJinput').querySelectorAll('input');
    for(input of inputsfill){
        if(input.checked & document.getElementById('ObjMarks').value===''){
            $("#alertText").text('Give Marks For Multiple Choice Question.')
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
            checkingC=1;
            return;
        }else if(input.checked & document.getElementById('ObjMarks').value !==''){checkingCInput++}}
        
    if(checkingC<1){
            var inputsmcq = document.getElementById('LNAinput').querySelectorAll('input');
            for(input of inputsmcq){
                if(input.checked & document.getElementById('LnaMarks').value===''){
                    $("#alertText").text('Give Marks For True and False Type Question.')
                    $("#alertBoxMain").css('display','flex').hide().fadeIn();
                    $("#alertConfirm").on("click",function(){
                        $("#alertBoxMain").fadeOut()
                    })
                    checkingC=1;
                    return;
                }
               else if(input.checked & document.getElementById('LnaMarks').value !==''){checkingCInput++}}}
   if(checkingC<1){
       var inputsonw = document.getElementById('VOCinput').querySelectorAll('input');
          for(input of inputsonw){
          if(input.checked & document.getElementById('VocMarks').value===''){
            $("#alertText").text('Give Marks For Match The Following Questions.')
                    $("#alertBoxMain").css('display','flex').hide().fadeIn();
                    $("#alertConfirm").on("click",function(){
                        $("#alertBoxMain").fadeOut()
                    })
          checkingC=1;
          return;
        }
       else if(input.checked & document.getElementById('VocMarks').value !==''){checkingCInput++}}}
   if(checkingC<1){
    var inputsonw = document.getElementById('GRMinput').querySelectorAll('input');
       for(input of inputsonw){
       if(input.checked & document.getElementById('GrmMarks').value===''){
        $("#alertText").text('Give Marks For Short Answer Question.')
        $("#alertBoxMain").css('display','flex').hide().fadeIn();
        $("#alertConfirm").on("click",function(){
            $("#alertBoxMain").fadeOut()
        })
       checkingC=1;
       return;
     }
    else if(input.checked & document.getElementById('GrmMarks').value !==''){checkingCInput++}}}   

  if(checkingC<1){
      var inputsonw = document.getElementById('WRTinput').querySelectorAll('input');
         for(input of inputsonw){
         if(input.checked & document.getElementById('WrtMarks').value===''){
            $("#alertText").text('Give Marks For Long Answer Question.')
        $("#alertBoxMain").css('display','flex').hide().fadeIn();
        $("#alertConfirm").on("click",function(){
            $("#alertBoxMain").fadeOut()
        })
         checkingC=1;
         return;
       }
      else if(input.checked & document.getElementById('WrtMarks').value !==''){checkingCInput++}}} 
      if(checkingC<1){
        var inputsonw = document.getElementById('OBJ2input').querySelectorAll('input');
           for(input of inputsonw){
           if(input.checked & document.getElementById('Obj2Marks').value===''){
              $("#alertText").text('Give Marks For Name the following Question')
          $("#alertBoxMain").css('display','flex').hide().fadeIn();
          $("#alertConfirm").on("click",function(){
              $("#alertBoxMain").fadeOut()
          })
           checkingC=1;
           return;
         }
        else if(input.checked & document.getElementById('Obj2Marks').value !==''){checkingCInput++}}}   
        if(checkingC<1){
            var inputsonw = document.getElementById('OBJ3input').querySelectorAll('input');
               for(input of inputsonw){
               if(input.checked & document.getElementById('Obj3Marks').value===''){
                  $("#alertText").text('Give Marks For Fill in the blanks.')
              $("#alertBoxMain").css('display','flex').hide().fadeIn();
              $("#alertConfirm").on("click",function(){
                  $("#alertBoxMain").fadeOut()
              })
               checkingC=1;
               return;
             }
            else if(input.checked & document.getElementById('Obj3Marks').value !==''){checkingCInput++}}} 
            if(checkingC<1){
                var inputsonw = document.getElementById('OBJ4input').querySelectorAll('input');
                   for(input of inputsonw){
                   if(input.checked & document.getElementById('Obj4Marks').value===''){
                      $("#alertText").text('Give Marks For Write the uses of the following blocks..')
                  $("#alertBoxMain").css('display','flex').hide().fadeIn();
                  $("#alertConfirm").on("click",function(){
                      $("#alertBoxMain").fadeOut()
                  })
                   checkingC=1;
                   return;
                 }
                else if(input.checked & document.getElementById('Obj4Marks').value !==''){checkingCInput++}}}      

        if(checkingC<1){
            console.log(checkingCInput)
            if(checkingCInput>0){gopass();}
            else{
                $("#alertText").text('Choose A Question To Continue')
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
            }
            }}

document.getElementById('QuestionMode').addEventListener('change',()=>{
    QuestionMode = document.getElementById('QuestionMode').value 
})
document.getElementById('top').children[0].addEventListener('change',()=>{
    if(document.getElementById('top').children[0].value === 'OBJ'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='block';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='none';}
    if(document.getElementById('top').children[0].value === 'LNA'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='block';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='none';}
    if(document.getElementById('top').children[0].value === 'VOC'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='Block';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='none';}
    if(document.getElementById('top').children[0].value === 'GRM'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='Block';document.getElementById('WrtMarks').style.display='none';}
    if(document.getElementById('top').children[0].value === 'WRT'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='Block';}
    if(document.getElementById('top').children[0].value === 'OBJ2'){document.getElementById('Obj2Marks').style.display='block';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='none';}
    if(document.getElementById('top').children[0].value === 'OBJ3'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='block';document.getElementById('Obj4Marks').style.display='none';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='none';}
    if(document.getElementById('top').children[0].value === 'OBJ4'){document.getElementById('Obj2Marks').style.display='none';document.getElementById('Obj3Marks').style.display='none';document.getElementById('Obj4Marks').style.display='block';document.getElementById('ObjMarks').style.display='none';document.getElementById('LnaMarks').style.display='none';document.getElementById('VocMarks').style.display='none';document.getElementById('GrmMarks').style.display='none';document.getElementById('WrtMarks').style.display='none';}
})




document.getElementById('next').addEventListener('click',()=>{
    if(pgno==4){sixpage();pgno++;document.getElementById('btngroup').style.display='flex';document.getElementById('next').style.display='none';document.getElementById('previous').style.top='-2%'}
    if(pgno==3){
        if(QuestionMode !== 'Auto'){
            if(customQuestionAllow==true){fifthpage();pgno++;document.getElementById('btngroup').style.display='none';document.getElementById('three').style.display='none';four();document.getElementById('four').style.display='block';document.getElementById('previous').style.left='0px';document.getElementById('next').style.left = '66vw';}
            else{
                
                $("#alertText").text('Selected Question Marks and Total Question Marks are different. Kindly change the Total Marks or Selected question.')
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
            }
        }
        else{
            if(autoQuestionAllow==true){fifthpage();pgno++;document.getElementById('btngroup').style.display='none';document.getElementById('three').style.display='none';four();document.getElementById('four').style.display='block';document.getElementById('previous').style.left='0px';document.getElementById('next').style.left = '66vw';}
            else{
                
                $("#alertText").text('Selected Question Marks and Total Question Marks are different. Kindly change the Total Marks or Selected question.')
                    $("#alertBoxMain").css('display','flex').hide().fadeIn();
                    $("#alertConfirm").on("click",function(){
                        $("#alertBoxMain").fadeOut()
                    })
            }
            
        }
    }
    if(pgno==2){if(QuestionMode === 'Auto'){step3()}else{step3c()}}
  // if(pgno==2){step3c()}
    if(pgno==1){thirdpage();pgno++;if(QuestionMode != 'Auto'){document.getElementById('customQuestion').style.display='block';}if(QuestionMode === 'Auto'){document.getElementById('selectQuestion').style.display='block';}document.getElementById('two').style.display='none';getval();resetInput();}
    if(pgno == 0){step1();}

})
/////////////////// random generator ////////////////
function getRandom(arr, n) {
    var result = new Array(n),
        len = arr.length,
        taken = new Array(len);
    if (n > len)
        throw new RangeError("getRandom: more elements taken than available");
    while (n--) {
        var x = Math.floor(Math.random() * len);
        result[n] = arr[x in taken ? taken[x] : x];
        taken[x] = --len in taken ? taken[len] : len;
    }
    return result;
}
//// question auto create //// .parentElement.previousSibling.innerHTML
function question(){
    var m1=0;var m2=0;var m3=0;var m4=0;var m5=0;var m6=0;var m7=0;var m8=0;
    document.getElementById('next').style.left = '43.5vw';
var ol = document.createElement('ol');
ol.setAttribute('id','question');
document.getElementById('three').append(ol)
var inputs = document.getElementById('selectQuestion').querySelectorAll('input')
for(input of inputs) {
    if(input.getAttribute('name') === 'Q'){
        if(input.value>0){
            if(input.parentElement.previousSibling.innerHTML.includes('Multiple Choice Question')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML +='<ol>'+ `${totalOl.length + 1 } ) <b>Tick (✓) the correct option. (`+ input.value + ' X '+ document.getElementsByClassName('span2')[0].children[1].children[1].value + ')</b></ol><br>';
                var f = getRandom(OBJ, input.value);
                m1= parseInt(input.value)*parseInt(document.getElementsByClassName('span2')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    ol.children[0].innerHTML += f[i];
                }}
            if(input.parentElement.previousSibling.innerHTML.includes('Write ‘T’ for true and ‘F’ for false statements')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML += '<br><ol id="mcq">' + `${totalOl.length + 1} ) <b>Write ‘T’ for true and ‘F’ for false statements  (`+ input.value + ' X '+ document.getElementsByClassName('span3')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(LNA, input.value);
                m2= parseInt(input.value)*parseInt(document.getElementsByClassName('span3')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    document.getElementById('mcq').innerHTML += f[i];
                }
            }
            if(input.parentElement.previousSibling.innerHTML.includes('Match The following Question')){
              //  ol.innerHTML += '<br><ol id="voctol">' +  <b>Objective Type Question  (`+ input.value + ' X '+ document.getElementsByClassName('span4')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(VOC, input.value)
                m3= parseInt(input.value)*parseInt(document.getElementsByClassName('span4')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    var totalOl = document.getElementById('question').querySelectorAll('ol');
                    document.getElementById('question').innerHTML += f[i];
                    var x = document.getElementById('question').querySelectorAll('.objectSerial');
                    x[x.length-1].innerHTML= `${totalOl.length + 1} )`;
                }
                var getObjectNo = document.getElementsByClassName('objectNo');
                for (let element of getObjectNo) {
                    element.innerHTML = `( 1 X ${document.getElementsByClassName('span4')[0].children[1].children[1].value} )`
                }
                var chkMatchTheFollowing = document.getElementById('question').querySelectorAll('.mf');
                if(chkMatchTheFollowing.length==2){
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[1].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[1].remove();
                    chkMatchTheFollowing[0].querySelector('.objectNo').innerHTML =`( 2 X ${document.getElementsByClassName('span4')[0].children[1].children[1].value} )`
                }else if(chkMatchTheFollowing.length==3){
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[1].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[2].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[1].remove();
                    chkMatchTheFollowing[2].remove();
                    chkMatchTheFollowing[0].querySelector('.objectNo').innerHTML =`( 3 X ${document.getElementsByClassName('span4')[0].children[1].children[1].value} )`
                }else if(chkMatchTheFollowing.length>3){
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[1].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[2].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[3].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[1].remove();
                    chkMatchTheFollowing[2].remove();
                    chkMatchTheFollowing[3].remove();
                    chkMatchTheFollowing[0].querySelector('.objectNo').innerHTML =`( 4 X ${document.getElementsByClassName('span4')[0].children[1].children[1].value} )`
                }
            }

            if(input.parentElement.previousSibling.innerHTML.includes('Short Answer Questions')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML += '<br><ol id="gratol">' + `${totalOl.length + 1} ) <b>Short Answer Questions   (`+ input.value + ' X '+ document.getElementsByClassName('span5')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(GRM, input.value)
                m4= parseInt(input.value)*parseInt(document.getElementsByClassName('span5')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    document.getElementById('gratol').innerHTML += f[i];
                }
            }
            if(input.parentElement.previousSibling.innerHTML.includes('Long Answer Questions')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML += '<br><ol id="wrtol">' + `${totalOl.length + 1} ) <b>Long Answer Questions  (`+ input.value + ' X '+ document.getElementsByClassName('span6')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(WRT, input.value)
                m5= parseInt(input.value)*parseInt(document.getElementsByClassName('span6')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    document.getElementById('wrtol').innerHTML += f[i];
                }
                
            }
            if(input.parentElement.previousSibling.innerHTML.includes('Name the following')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML += '<br><ol id="nameTheFollowing">' + `${totalOl.length + 1} ) <b>Name the following.  (`+ input.value + ' X '+ document.getElementsByClassName('span7')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(OBJ2, input.value)
                m6= parseInt(input.value)*parseInt(document.getElementsByClassName('span7')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    document.getElementById('nameTheFollowing').innerHTML += f[i];
                }
                
            }
            if(input.parentElement.previousSibling.innerHTML.includes('Fill in the blanks')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML += '<br><ol id="fullForm">' + `${totalOl.length + 1} ) <b>Fill in the blanks.  (`+ input.value + ' X '+ document.getElementsByClassName('span8')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(OBJ3, input.value)
                m7= parseInt(input.value)*parseInt(document.getElementsByClassName('span8')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    document.getElementById('fullForm').innerHTML += f[i];
                }
                
            }
            if(input.parentElement.previousSibling.innerHTML.includes('Write the full forms of the following Logo commands')){
                var qObj = document.createElement('ol');
                var totalOl = document.getElementById('question').querySelectorAll('ol')
                ol.innerHTML += '<br><ol id="useBlock">' + `${totalOl.length + 1} ) <b>Write the full forms of the following Logo commands.  (`+ input.value + ' X '+ document.getElementsByClassName('span9')[0].children[1].children[1].value + ')</b></ol>';
                var f = getRandom(OBJ4, input.value)
                m8= parseInt(input.value)*parseInt(document.getElementsByClassName('span9')[0].children[1].children[1].value)
                for (let i = 0; i < f.length; i++) {
                    document.getElementById('useBlock').innerHTML += f[i];
                }
                
            }

            
        }
    }
}
var totalMarks = 0;
totalMarks= m1+m2+m3+m4+m5+m6+m7+m8;
    document.getElementById('SelectMarks').innerText = `Selected Marks - ${totalMarks}`;
if(totalMarks == parseInt(document.getElementById('TotalMarks').value)){
    document.getElementById('SelectMarks').style.backgroundColor = 'rgb(45 168 14)',autoQuestionAllow=true;
}else{
    document.getElementById('SelectMarks').style.backgroundColor = 'rgb(200 0 0)',autoQuestionAllow=false;
}
////// ans show for teacher ////////
if(document.getElementById('QuestionType').value ==='Students'){
    for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
        const element = document.getElementsByClassName('ans')[index];
        
        element.style.display='none'
    }
 }else{
    for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
        const element = document.getElementsByClassName('ans')[index];
        
        element.style.display='block'
    }
 }
}

////////////////  question custom create /////
function cquestion(){
    var totalMarks = 0;
    
    var ol = document.createElement('ol');
    ol.setAttribute('id','question');
    document.getElementById('three').append(ol)
    var inputs = document.getElementById('customQuestion').querySelectorAll('input');
    var chkMatchTotal=0;
    for(input of inputs){
        if(input.checked){
            ////////   Multiple Choice Question ///////////
            if(input.parentElement.parentElement.id.includes('Obj')){
                if(document.getElementById('qObj') == null){
                    var qObj = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                qObj.innerHTML = totalOl.length + 1 + `)  Answer The Following Multiple Choice Question. ( <text id=fno>1</text> X ${ObjMarks.value} )`;
                qObj.setAttribute('id','qObj')
                qObj.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qObj)
                }
                else{
                    document.getElementById('qObj').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('fno').innerText = parseInt(document.getElementById('fno').innerText) + 1;
                }
            }
            //////// Long Answer Question ///////////
            if(input.parentElement.parentElement.id.includes('Lna')){
                console.log(input);
                if(document.getElementById('qLna') == null){
                    var qLna = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                qLna.innerHTML = `<br><br> ${totalOl.length + 1})  Write ‘T’ for true and ‘F’ for false statements. . ( <text id=MCQno>1</text> X ${LnaMarks.value} )`;
                qLna.setAttribute('id','qLna')
                qLna.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qLna)
                }
                else{
                    document.getElementById('qLna').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('MCQno').innerText = parseInt(document.getElementById('MCQno').innerText) + 1;
                }
            }
            ///////////////// vocabulary ///////////////////
            if(input.parentElement.parentElement.id.includes('Voc')){
                // if(document.getElementById('qVoc') == null){
                //     var qVoc = document.createElement('ol');
                //     var totalOl = document.getElementById('question').querySelectorAll('ol')
                // qVoc.innerHTML = `<br><br> ${totalOl.length + 1})  Answer The Following Objective Type Question . ( <text id=ONWno>1</text> X ${VocMarks.value} )`;
                // qVoc.setAttribute('id','qVoc')
                // qVoc.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                // document.getElementById('question').append(qVoc)
                // }
                // else{
                //     document.getElementById('qVoc').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('ONWno').innerText = parseInt(document.getElementById('ONWno').innerText) + 1;
                // }
                
                    
                    var totalOl = document.getElementById('question').querySelectorAll('ol');
                    if(input.nextElementSibling.nextElementSibling.getAttribute('class')=='mf'){
                        chkMatchTotal+=1;
                        document.getElementById('question').innerHTML += `<br><ol style='list-style: lower-roman;' class='mf'> ${input.nextElementSibling.nextElementSibling.innerHTML} </ol>`;
                    }else{
                        document.getElementById('question').innerHTML += `<br><ol style='list-style: none;'> ${input.nextElementSibling.nextElementSibling.innerHTML} </ol>`;
                    }
                 
                    var x = document.getElementById('question').querySelectorAll('.objectSerial');
                    x[x.length-1].innerHTML= `${totalOl.length + 1} )`;
                
                var getObjectNo = document.getElementById('question').getElementsByClassName('objectNo');

                getObjectNo[getObjectNo.length-1].innerHTML = `( 1 X ${VocMarks.value} )`
                
               
                var chkMatchTheFollowing = document.getElementById('question').querySelectorAll('.mf');
                if(chkMatchTheFollowing.length>1){
                    chkMatchTheFollowing[0].querySelector('.objectNo').innerHTML =`( ${chkMatchTotal} X ${VocMarks.value} )`  
                    chkMatchTheFollowing[0].innerHTML += `<li style="left:25px">${chkMatchTheFollowing[1].querySelector('li').innerHTML} </li>` ;
                    chkMatchTheFollowing[1].remove();
                    totalMarks+=parseInt(VocMarks.value);
                }else{ totalMarks+=parseInt(VocMarks.value);}
            }
            
            /////////////  Grammer //////////
            if(input.parentElement.parentElement.id.includes('Grm')){
                if(document.getElementById('qGrm') == null){
                    var qGrm = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                qGrm.innerHTML = `<br><br> ${totalOl.length + 1})  Answer The Following Short Type Question . ( <text id=Grmno>1</text> X ${GrmMarks.value} )`;
                qGrm.setAttribute('id','qGrm')
                qGrm.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qGrm)
                }
                else{
                    document.getElementById('qGrm').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('Grmno').innerText = parseInt(document.getElementById('Grmno').innerText) + 1;
                }
            }
            /////////////  Writing //////////
            if(input.parentElement.parentElement.id.includes('Wrt')){
                if(document.getElementById('qWrt') == null){
                    var qWrt = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                qWrt.innerHTML = `<br><br> ${totalOl.length + 1})  Answer The Following Long Type Question . ( <text id=Wrtno>1</text> X ${WrtMarks.value} )`;
                qWrt.setAttribute('id','qWrt')
                qWrt.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qWrt)
                }
                else{
                    document.getElementById('qWrt').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('Wrtno').innerText = parseInt(document.getElementById('Wrtno').innerText) + 1;
                }
            }
            if(input.parentElement.parentElement.id.includes('OBJ2')){
                if(document.getElementById('Obj2') == null){
                    var qObj2 = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                    qObj2.innerHTML = `<br><br> ${totalOl.length + 1})  Name the following Question . ( <text id=Obj2no>1</text> X ${Obj2Marks.value} )`;
                    qObj2.setAttribute('id','Obj2')
                    qObj2.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qObj2)
                }
                else{
                    document.getElementById('Obj2').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('Obj2no').innerText = parseInt(document.getElementById('Obj2no').innerText) + 1;
                }
            }
            if(input.parentElement.parentElement.id.includes('OBJ3')){
                if(document.getElementById('Obj3') == null){
                    var qObj3 = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                    qObj3.innerHTML = `<br><br> ${totalOl.length + 1})  Fill in the blanks.( <text id=Obj3no>1</text> X ${Obj3Marks.value} )`;
                    qObj3.setAttribute('id','Obj3')
                    qObj3.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qObj3)
                }
                else{
                    document.getElementById('Obj3').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('Obj3no').innerText = parseInt(document.getElementById('Obj3no').innerText) + 1;
                }
            }
            if(input.parentElement.parentElement.id.includes('OBJ4')){
                if(document.getElementById('Obj4') == null){
                    var qObj4 = document.createElement('ol');
                    var totalOl = document.getElementById('question').querySelectorAll('ol')
                    qObj4.innerHTML = `<br><br> ${totalOl.length + 1})  Write the full forms of the following Logo commands. ( <text id=Obj4no>1</text> X ${Obj4Marks.value} )`;
                    qObj4.setAttribute('id','Obj4')
                    qObj4.innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`
                document.getElementById('question').append(qObj4)
                }
                else{
                    document.getElementById('Obj4').innerHTML += `<li > ${input.nextElementSibling.innerHTML} </li>`;document.getElementById('Obj4no').innerText = parseInt(document.getElementById('Obj4no').innerText) + 1;
                }
            }
        }
       
    }
    
    if(document.getElementById('qObj') !== null){
        totalMarks+= (parseInt(ObjMarks.value)*parseInt(document.getElementById('fno').innerText));
    }
    if(document.getElementById('qLna') !== null){
        totalMarks+= (parseInt(LnaMarks.value)*parseInt(document.getElementById('MCQno').innerText));
    }
    // if(document.getElementById('qVoc') !== null){
    //     totalMarks+= (parseInt(VocMarks.value)*parseInt(document.getElementById('ONWno').innerText));
    // }
  //   totalMarks+= parseInt(document.getElementById('question').querySelectorAll('.objectSerial').length)*parseInt(VocMarks.value);

    if(document.getElementById('qGrm') !== null){
        totalMarks+= (parseInt(GrmMarks.value)*parseInt(document.getElementById('Grmno').innerText));
    }
    if(document.getElementById('qWrt') !== null){
        totalMarks+= (parseInt(WrtMarks.value)*parseInt(document.getElementById('Wrtno').innerText));
    }
    if(document.getElementById('Obj4') !== null){
        totalMarks+= (parseInt(Obj4Marks.value)*parseInt(document.getElementById('Obj4no').innerText));
    }
    if(document.getElementById('Obj3') !== null){
        totalMarks+= (parseInt(Obj3Marks.value)*parseInt(document.getElementById('Obj3no').innerText));
    }
    if(document.getElementById('Obj2') !== null){
        totalMarks+= (parseInt(Obj2Marks.value)*parseInt(document.getElementById('Obj2no').innerText));
    }
    
    document.getElementById('SelectMarks').innerText = `Selected Marks - ${totalMarks}`;
    if(totalMarks == parseInt(document.getElementById('TotalMarks').value)){
        document.getElementById('SelectMarks').style.backgroundColor = 'rgb(45 168 14)',customQuestionAllow=true;
    }else{
        document.getElementById('SelectMarks').style.backgroundColor = 'rgb(200 0 0)',customQuestionAllow=false;
    }
    ////// ans show for teacher ////////
    if(document.getElementById('QuestionType').value ==='Students'){
        for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
            const element = document.getElementsByClassName('ans')[index];
            
            element.style.display='none'
        }
     }else{
        for (let index = 0; index < document.getElementsByClassName('ans').length; index++) {
            const element = document.getElementsByClassName('ans')[index];
            
            element.style.display='block'
        }
     }
     
}    

function getval(){
    var chks = document.getElementById('two').querySelectorAll('input');
    for(input of chks){
        if(input.checked){
            fillno.push(input.name)
            getvalueall();
        }
        ///// to calculate fill in blanks total no /////////////////////////////////
    }
    document.querySelector('.span2').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ OBJ.length + `]` ;  
    document.querySelector('.span3').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ LNA.length + `]` ;  
    document.querySelector('.span4').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ VOC.length + `]` ;
    document.querySelector('.span5').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ GRM.length + `]` ;
    document.querySelector('.span6').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ WRT.length + `]` ;
    document.querySelector('.span7').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ OBJ2.length + `]` ;
    document.querySelector('.span8').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ OBJ3.length + `]` ;
    document.querySelector('.span9').children[0].innerHTML += `&nbsp; &nbsp; &nbsp;[`+ OBJ4.length + `]` ;

}

///// to calculate fill in blanks total no /////////////////////////////////
function getvalueall(){

 if(input.name === 'chapter1'){
    for (let i = 0; i < LESSON1[0].MCQ.length ; i++) {
        OBJ.push(LESSON1[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON1[1].TF.length ; i++) {
        LNA.push(LESSON1[1].TF[i])  
    }
    for (let i = 0; i < LESSON1[2].OBJ2.length ; i++) {
        OBJ2.push(LESSON1[2].OBJ2[i])  
    }
    // for (let i = 0; i < LESSON1[2].OBJ.length ; i++) {
    //     VOC.push(LESSON1[2].OBJ[i])    
    // }
    for (let i = 0; i < LESSON1[3].GRM.length ; i++) {
        GRM.push(LESSON1[3].GRM[i])    
    }
    for (let i = 0; i < LESSON1[4].WRT.length ; i++) {
        WRT.push(LESSON1[4].WRT[i])    
    } 
 }
 if(input.name === 'chapter2'){
    for (let i = 0; i < LESSON2[0].MCQ.length ; i++) {
        OBJ.push(LESSON2[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON2[1].TF.length ; i++) {
        LNA.push(LESSON2[1].TF[i])  
    }
    for (let i = 0; i < LESSON2[2].OBJ.length ; i++) {
        VOC.push(LESSON2[2].OBJ[i])    
    }
    for (let i = 0; i < LESSON2[3].GRM.length ; i++) {
        GRM.push(LESSON2[3].GRM[i])    
    }
    for (let i = 0; i < LESSON2[4].WRT.length ; i++) {
        WRT.push(LESSON2[4].WRT[i])    
    }
 }
 if(input.name === 'chapter3'){
    for (let i = 0; i < LESSON3[0].MCQ.length ; i++) {
        OBJ.push(LESSON3[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON3[1].TF.length ; i++) {
        LNA.push(LESSON3[1].TF[i])  
    }
    for (let i = 0; i < LESSON3[2].OBJ2.length ; i++) {
        OBJ2.push(LESSON3[2].OBJ2[i])    
    }
    for (let i = 0; i < LESSON3[3].GRM.length ; i++) {
        GRM.push(LESSON3[3].GRM[i])    
    }
    for (let i = 0; i < LESSON3[4].WRT.length ; i++) {
        WRT.push(LESSON3[4].WRT[i])    
    }
 }
 if(input.name === 'chapter4'){
    for (let i = 0; i < LESSON4[0].MCQ.length ; i++) {
        OBJ.push(LESSON4[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON4[1].TF.length ; i++) {
        LNA.push(LESSON4[1].TF[i])  
    }
    for (let i = 0; i < LESSON4[2].OBJ.length ; i++) {
        VOC.push(LESSON4[2].OBJ[i])    
    }
    for (let i = 0; i < LESSON4[3].GRM.length ; i++) {
        GRM.push(LESSON4[3].GRM[i])    
    }
    for (let i = 0; i < LESSON4[4].WRT.length ; i++) {
        WRT.push(LESSON4[4].WRT[i])    
    }
 }
 if(input.name === 'chapter5'){
    for (let i = 0; i < LESSON5[0].MCQ.length ; i++) {
        OBJ.push(LESSON5[0].MCQ[i])  
    }
    // for (let i = 0; i < LESSON5[1].TF.length ; i++) {
    //     LNA.push(LESSON5[1].TF[i])  
    // }
    for (let i = 0; i < LESSON5[1].OBJ3.length ; i++) {
        OBJ3.push(LESSON5[1].OBJ3[i])    
    }
    for (let i = 0; i < LESSON5[2].OBJ4.length ; i++) {
        OBJ4.push(LESSON5[2].OBJ4[i])    
    }
    for (let i = 0; i < LESSON5[3].GRM.length ; i++) {
        GRM.push(LESSON5[3].GRM[i])    
    }
    for (let i = 0; i < LESSON5[4].WRT.length ; i++) {
        WRT.push(LESSON5[4].WRT[i])    
    }
 }
 if(input.name === 'chapter6'){
    for (let i = 0; i < LESSON6[0].MCQ.length ; i++) {
        OBJ.push(LESSON6[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON6[1].TF.length ; i++) {
        LNA.push(LESSON6[1].TF[i])  
    }
    for (let i = 0; i < LESSON6[2].OBJ.length ; i++) {
        VOC.push(LESSON6[2].OBJ[i])    
    }
    for (let i = 0; i < LESSON6[3].GRM.length ; i++) {
        GRM.push(LESSON6[3].GRM[i])    
    }
    for (let i = 0; i < LESSON6[4].WRT.length ; i++) {
        WRT.push(LESSON6[4].WRT[i])    
    }
 }
 if(input.name === 'chapter7'){
    for (let i = 0; i < LESSON7[0].MCQ.length ; i++) {
        OBJ.push(LESSON7[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON7[1].TF.length ; i++) {
        LNA.push(LESSON7[1].TF[i])  
    }
    for (let i = 0; i < LESSON7[2].OBJ.length ; i++) {
        VOC.push(LESSON7[2].OBJ[i])    
    }
    for (let i = 0; i < LESSON7[3].GRM.length ; i++) {
        GRM.push(LESSON7[3].GRM[i])    
    }
    for (let i = 0; i < LESSON7[4].WRT.length ; i++) {
        WRT.push(LESSON7[4].WRT[i])    
    }
 }
 if(input.name === 'chapter8'){
    for (let i = 0; i < LESSON8[0].MCQ.length ; i++) {
        OBJ.push(LESSON8[0].MCQ[i])  
    }
    for (let i = 0; i < LESSON8[1].TF.length ; i++) {
        LNA.push(LESSON8[1].TF[i])  
    }
    for (let i = 0; i < LESSON8[2].OBJ4.length ; i++) {
        OBJ4.push(LESSON8[2].OBJ4[i])    
    }
    for (let i = 0; i < LESSON8[3].GRM.length ; i++) {
        GRM.push(LESSON8[3].GRM[i])    
    }
    for (let i = 0; i < LESSON8[4].WRT.length ; i++) {
        WRT.push(LESSON8[4].WRT[i])    
    }
 }
}
function allOff(){
    document.getElementById('OBJinput').style.display = 'none';
    document.getElementById('OBJ2input').style.display = 'none';
    document.getElementById('OBJ3input').style.display = 'none';
    document.getElementById('OBJ4input').style.display = 'none';
    document.getElementById('LNAinput').style.display = 'none';
    document.getElementById('VOCinput').style.display = 'none';
    document.getElementById('GRMinput').style.display = 'none';
    document.getElementById('WRTinput').style.display = 'none';
}
function allListOff(){
      document.getElementById('OptionChange').value='';
     var a = document.getElementById('OBJinput').querySelectorAll('input');
     for (let i = 0; i < a.length; i++) {
        a[i].checked=false;  
     };
     allOff();
}
////////////////  getting list for fill blanks and mcq ///////////////////
document.getElementById('top').children[0].addEventListener('change',()=>{
    if(document.getElementById('top').children[0].value === ''){
        allOff();
    }
    if(document.getElementById('top').children[0].value === 'OBJ'){
       document.getElementById('OBJinput').style.display = 'block';
       document.getElementById('LNAinput').style.display = 'none';
       document.getElementById('VOCinput').style.display = 'none';
       document.getElementById('GRMinput').style.display = 'none';
       document.getElementById('WRTinput').style.display = 'none';
       document.getElementById('OBJ2input').style.display = 'none';
       document.getElementById('OBJ3input').style.display = 'none';
       document.getElementById('OBJ4input').style.display = 'none';
       
       
       if(fillno.includes('chapter1')){
        document.getElementById('chp1Obj').style.display = 'block';
       }
       if(fillno.includes('chapter2')){
        document.getElementById('chp2Obj').style.display = 'block';
       }
       if(fillno.includes('chapter3')){
        document.getElementById('chp3Obj').style.display = 'block';
       }
       if(fillno.includes('chapter4')){
        document.getElementById('chp4Obj').style.display = 'block';
       }
       if(fillno.includes('chapter5')){
        document.getElementById('chp5Obj').style.display = 'block';
       }
       if(fillno.includes('chapter6')){
        document.getElementById('chp6Obj').style.display = 'block';
       }
       if(fillno.includes('chapter7')){
        document.getElementById('chp7Obj').style.display = 'block';
       }
       if(fillno.includes('chapter8')){
        document.getElementById('chp8Obj').style.display = 'block';
       }
    }
    if(document.getElementById('top').children[0].value === 'LNA'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'block';
        document.getElementById('VOCinput').style.display = 'none';
        document.getElementById('GRMinput').style.display = 'none';
        document.getElementById('WRTinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'none';
        document.getElementById('OBJ3input').style.display = 'none';
        document.getElementById('OBJ4input').style.display = 'none';
        if(fillno.includes('chapter1')){
         document.getElementById('chp1Lna').style.display = 'block';
        }
        if(fillno.includes('chapter2')){
         document.getElementById('chp2Lna').style.display = 'block';
        }
        if(fillno.includes('chapter3')){
            document.getElementById('chp3Lna').style.display = 'block';
        }
        if(fillno.includes('chapter4')){
         document.getElementById('chp4Lna').style.display = 'block';
        }
        // if(fillno.includes('chapter5')){
        //  document.getElementById('chp5Lna').style.display = 'block';
        // }
        if(fillno.includes('chapter6')){
         document.getElementById('chp6Lna').style.display = 'block';
        }
        if(fillno.includes('chapter7')){
            document.getElementById('chp7Lna').style.display = 'block';
           }
           if(fillno.includes('chapter8')){
            document.getElementById('chp8Lna').style.display = 'block';
           }
     }
     if(document.getElementById('top').children[0].value === 'VOC'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'none';
        document.getElementById('VOCinput').style.display = 'block';
        document.getElementById('GRMinput').style.display = 'none';
        document.getElementById('WRTinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'none';
        document.getElementById('OBJ3input').style.display = 'none';
        document.getElementById('OBJ4input').style.display = 'none';
        // if(fillno.includes('chapter1')){
        //  document.getElementById('chp1Voc').style.display = 'block';
        // }
        if(fillno.includes('chapter2')){
         document.getElementById('chp2Voc').style.display = 'block';
        }
        // if(fillno.includes('chapter3')){
        //     document.getElementById('chp3Voc').style.display = 'block';
        // }
        if(fillno.includes('chapter4')){
            document.getElementById('chp4Voc').style.display = 'block';
        }
        // if(fillno.includes('chapter5')){
        //     document.getElementById('chp5Voc').style.display = 'block';
        // }
        if(fillno.includes('chapter6')){
            document.getElementById('chp6Voc').style.display = 'block';
        }
        if(fillno.includes('chapter7')){
            document.getElementById('chp7Voc').style.display = 'block';
        }
     }
     if(document.getElementById('top').children[0].value === 'GRM'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'none';
        document.getElementById('VOCinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'none';
        document.getElementById('OBJ3input').style.display = 'none';
        document.getElementById('OBJ4input').style.display = 'none';
        document.getElementById('GRMinput').style.display = 'block';
        document.getElementById('WRTinput').style.display = 'none';
        if(fillno.includes('chapter1')){
            document.getElementById('chp1Grm').style.display = 'block';
           }
           if(fillno.includes('chapter2')){
            document.getElementById('chp2Grm').style.display = 'block';
           }
           if(fillno.includes('chapter3')){
            document.getElementById('chp3Grm').style.display = 'block';
           }
           if(fillno.includes('chapter4')){
            document.getElementById('chp4Grm').style.display = 'block';
           }
           if(fillno.includes('chapter5')){
            document.getElementById('chp5Grm').style.display = 'block';
           }
           if(fillno.includes('chapter6')){
            document.getElementById('chp6Grm').style.display = 'block';
           }
           if(fillno.includes('chapter7')){
            document.getElementById('chp7Grm').style.display = 'block';
           }
           if(fillno.includes('chapter8')){
            document.getElementById('chp8Grm').style.display = 'block';
           }
     }
     if(document.getElementById('top').children[0].value === 'WRT'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'none';
        document.getElementById('VOCinput').style.display = 'none';
        document.getElementById('GRMinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'none';
        document.getElementById('OBJ3input').style.display = 'none';
        document.getElementById('OBJ4input').style.display = 'none';
        document.getElementById('WRTinput').style.display = 'block';
           if(fillno.includes('chapter1')){
            document.getElementById('chp1Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter2')){
            document.getElementById('chp2Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter3')){
            document.getElementById('chp3Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter4')){
            document.getElementById('chp4Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter5')){
            document.getElementById('chp5Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter6')){
            document.getElementById('chp6Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter7')){
            document.getElementById('chp7Wrt').style.display = 'block';
           }
           if(fillno.includes('chapter8')){
            document.getElementById('chp8Wrt').style.display = 'block';
           }
     }
     if(document.getElementById('top').children[0].value === 'OBJ2'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'none';
        document.getElementById('VOCinput').style.display = 'none';
        document.getElementById('GRMinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'block';
        document.getElementById('OBJ3input').style.display = 'none';
        document.getElementById('OBJ4input').style.display = 'none';
        document.getElementById('WRTinput').style.display = 'none';
           if(fillno.includes('chapter1')){
            document.getElementById('chp1OBJ2').style.display = 'block';
           }
           if(fillno.includes('chapter3')){
               document.getElementById('chp3OBJ2').style.display = 'block';
           }
     }
     if(document.getElementById('top').children[0].value === 'OBJ3'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'none';
        document.getElementById('VOCinput').style.display = 'none';
        document.getElementById('GRMinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'none';
        document.getElementById('OBJ3input').style.display = 'block';
        document.getElementById('OBJ4input').style.display = 'none';
        document.getElementById('WRTinput').style.display = 'none';
           if(fillno.includes('chapter5')){
            document.getElementById('chp5OBJ3').style.display = 'block';
           }
     }
     if(document.getElementById('top').children[0].value === 'OBJ4'){
        document.getElementById('OBJinput').style.display = 'none';
        document.getElementById('LNAinput').style.display = 'none';
        document.getElementById('VOCinput').style.display = 'none';
        document.getElementById('GRMinput').style.display = 'none';
        document.getElementById('OBJ2input').style.display = 'none';
        document.getElementById('OBJ3input').style.display = 'none';
        document.getElementById('OBJ4input').style.display = 'block';
        document.getElementById('WRTinput').style.display = 'none';
           if(fillno.includes('chapter5')){
            document.getElementById('chp5OBJ4').style.display = 'block';
           }
           if(fillno.includes('chapter8')){
            document.getElementById('chp8OBJ4').style.display = 'block';
           }
     }
})

document.getElementById('previous').addEventListener('click',()=>{
    if(pgno ==1){fstpage();one.style.display='block';two.style.display='none';pgno--;document.getElementById('previous').style.display='none'}
    if(pgno ==2){secpage();allListOff();two.style.display='block';document.getElementById('selectQuestion').style.display='none';document.getElementById('customQuestion').style.display='none';
    document.getElementsByClassName('span9')[0].children[0].innerText='Write the full forms of the following Logo commands.';
    document.getElementsByClassName('span8')[0].children[0].innerText='Fill in the blanks.';
    document.getElementsByClassName('span7')[0].children[0].innerText='Name the following Question';
    document.getElementsByClassName('span6')[0].children[0].innerText='Long Answer Questions';
    document.getElementsByClassName('span5')[0].children[0].innerText='Short Answer Questions';
    document.getElementsByClassName('span4')[0].children[0].innerText='Match The following Question';
    document.getElementsByClassName('span3')[0].children[0].innerText='Write ‘T’ for true and ‘F’ for false statements';
    document.getElementsByClassName('span2')[0].children[0].innerText='Multiple Choice Question';
    pgno--;OBJ= [];OBJ2= [];OBJ3= [];OBJ4= [];
    LNA = [];VOC = []; GRM = [];WRT = [];fillno=[]}
    if(pgno ==3){thirdpage();if(QuestionMode != 'Auto'){document.getElementById('customQuestion').style.display='block';}if(QuestionMode === 'Auto'){document.getElementById('selectQuestion').style.display='block';}three.style.display='none';pgno--;document.getElementById('next').style.left= '66vw;';document.getElementById('previous').style.left= '0px';document.getElementById('question').remove();document.getElementById('next').style.left='66vw'}
    if(pgno ==4){forthpage();document.getElementById('previous').style.top='-13.2%';document.getElementById('previous').style.left='-23vw';three.style.display='block';document.getElementById('four').style.display='none';pgno--;document.getElementById('next').style.display='block';document.getElementById('next').style.left='43.3vw';document.getElementById('fourContainer').innerHTML='<span id="firstpart" style=" margin-left: 0.5in; width: 100%;"></span>'}
    if(pgno ==5){fifthpage();document.getElementById('btngroup').style.display='none';document.getElementById('next').style.display='block';document.getElementById('previous').style.top='-13.1%';pgno--;}
})

document.getElementsByClassName('span2')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(OBJ.length!= 0){
            if(e.target.value > OBJ.length || e.target.value<0){
                e.target.value='';
                $("#alertText").text(`Choose Between ${OBJ.length} Questions`)
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
               
            }
        }
        else{e.target.value='';}
    }
})
document.getElementsByClassName('span3')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(LNA.length!= 0){
          if(e.target.value > LNA.length || e.target.value<0){
             e.target.value='';
             $("#alertText").text(`Choose Between ${LNA.length} Questions`)
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
          
          }
}else{e.target.value='';}
}
})
document.getElementsByClassName('span4')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(VOC.length!= 0){
    if(e.target.value > VOC.length || e.target.value<0){
        e.target.value='';
       
        $("#alertText").text(`Choose Between ${VOC.length} Questions`)
        $("#alertBoxMain").css('display','flex').hide().fadeIn();
        $("#alertConfirm").on("click",function(){
            $("#alertBoxMain").fadeOut()
        })
    }}else{e.target.value='';}
}
})
document.getElementsByClassName('span5')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(GRM.length!= 0){
    if(e.target.value > GRM.length || e.target.value<0){
        e.target.value='';
        
        $("#alertText").text(`Choose Between ${GRM.length} Questions`)
        $("#alertBoxMain").css('display','flex').hide().fadeIn();
        $("#alertConfirm").on("click",function(){
            $("#alertBoxMain").fadeOut()
        })
    }}else{e.target.value='';}
}
})
document.getElementsByClassName('span6')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(WRT.length!= 0){
    if(e.target.value > WRT.length || e.target.value<0){
        e.target.value='';
        
        $("#alertText").text(`Choose Between ${WRT.length} Questions`)
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
    }}else{e.target.value='';}
}
})
document.getElementsByClassName('span7')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(OBJ2.length!= 0){
    if(e.target.value > OBJ2.length || e.target.value<0){
        e.target.value='';
        
        $("#alertText").text(`Choose Between ${OBJ2.length} Questions`)
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
    }}else{e.target.value='';}
}
})
document.getElementsByClassName('span8')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(OBJ3.length!= 0){
    if(e.target.value > OBJ3.length || e.target.value<0){
        e.target.value='';
        
        $("#alertText").text(`Choose Between ${OBJ3.length} Questions`)
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
    }}else{e.target.value='';}
}
})
document.getElementsByClassName('span9')[0].addEventListener('change',(e)=>{
    if(e.target.getAttribute('name')==='Q'){
        if(OBJ4.length!= 0){
    if(e.target.value > OBJ4.length || e.target.value<0){
        e.target.value='';
        
        $("#alertText").text(`Choose Between ${OBJ4.length} Questions`)
                $("#alertBoxMain").css('display','flex').hide().fadeIn();
                $("#alertConfirm").on("click",function(){
                    $("#alertBoxMain").fadeOut()
                })
    }}else{e.target.value='';}
}
})
///// clear pgno2 input value previous ///////////////
function resetInput(){var all  = document.getElementById('selectQuestion').querySelectorAll('input')
for(input of all){
    input.value='';
}}
